export default {
  subject: "Erasure Request",
  formatBody(data) {
    const date = new Date();
    var body = `${date.toLocaleDateString('en-GB')}
    
To whom it may concern:

I am writing to request that you erase all my personal information from all your information systems pursuant to Article 17 of the General Data Protection Regulation (GDPR). Please confirm that you have erased my personal information, and that you have followed up with any organization with whom my information has been shared.

If you need any further information from me in order to locate my records in your systems, please let me know as soon as possible. My preferred method of contact is email. 

If you do not normally deal with these requests, please pass along this letter to your Data Protection Officer. Please note that you have 30 days to comply with this request.

`;

if (data.identifyingInfo) {
	body = body.concat(
`Please use the following information to identify me in your systems:
${data.identifyingInfo}

`);
}

return body.concat(`Regards,

${data.name}


---------------------------
This email was generated by https://opt-out.eu.

If your organization has a different email address for dealing with GDPR requests please let us know by filling in the following form:
https://docs.google.com/forms/d/e/1FAIpQLScZRj7Y1RA6c5zWst-bTS2tAR-eazPTtubMzo9TsqC4m5xc3Q/viewform?entry.123933693=${
      data.companyName
    } 
`);
  }
};
