import capitalize from "../utils/capitalize";
import dateFormatter from "../utils/date-formatter";
import daysSince from "../utils/days-since";
import Regulations from "../../utils/regulations";

export default {
  subject(data) {
    const regulation = Regulations[data.requestType];
    const requestType = regulation['requestTypes'][data.requestType];
    return `Complaint against ${data.companyName} regarding a ${data.regulationType} data ${requestType} request.`;
  },
  body(data) {
    const regulation = Regulations[data.requestType];
    const requestType = regulation['requestTypes'][data.requestType];
    const bodyParts = [];

    bodyParts.push('Dear Data Protection Agency,');
    bodyParts.push(`On ${dateFormatter(new Date(data.requestDate))} I have sent ${data.companyName} a data ${requestType.name} request pursuant to article ${requestType.artivle} of the ${regulation.longName} (${regulation.displayName}).`);

    if (data.reminderEmailsSent) {
      bodyParts.push(`I have also sent the organization a reminder email on ${dateFormatter(new Date(data.reminderEmailsSentDate))}.`);
    }

    let reason = '';
    if (data.status === 'PARTIAL') {
      reason = 'the organization failed to fully comply with my request';
    } else if (data.status === 'DECLINED') {
      reason = 'the organization declined to comply with my request';
    } else if (data.status === 'NO_REPLY') {
      reason = 'the organization did not reply to my request';
    }
    bodyParts.push(`I would like to submit a complaint because ${reason}.`);

    if (data.escalationDetails) {
      bodyParts.push(`${data.escalationDetails}`);
    }

    const daysSinceRequest = daysSince(new Date(data.requestDate));
    bodyParts.push(`Since it has been ${daysSinceRequest} days since the request was sent I would like to file a complaint with you. Please keep me updated as to the status of your investigation. Please let me know if you would like me to provide any additional information. My preferred method of communication is email.`);
    
    /* bodyParts.push(`The original request was emailed from my personal email address. The text of the email was generated by YourDigitalRights.org, a website which automates the process of filing data requests. The service has kindly kept a record of my request which you can view here.`); */
    
    bodyParts.push(`I have CC’d ${data.companyName} to this email.}`);
    bodyParts.push('Kind regards,');
    bodyParts.push(`${data.name}`);
    
    return bodyParts.join('\n\n');
  },
};
